apiVersion: v1
kind: Service
metadata:
  name: node-port-ip-service-for-nginx #node port given name
spec:
  type: NodePort
  selector:
    app: webapp #node-port-ip name (using same name we bind node-port service to pod. pod also have same name)
  ports:
    - name: http
      port: 8080        # service port
      targetPort: 80    # Pod container port
      nodePort: 30001   # node port
