apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment #name of deployement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx-c
          image: nginx:latest
          ports:
            - containerPort: 80