apiVersion: v1
kind: Service
metadata:
  name: my-nlb-web-app
  namespace: dev-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb   #if we didnt mention annotation then it default create classic load balancer
    service.beta.kubernetes.io/aws-load-balancer-name: my-nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80
