apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: dev-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 3000
